name: 'Python test and deloy GHaction'
description: 'Reusable GHaction for build/test/deploy Oarepo python packages.'
inputs:
  use-elasticsearch:
    description: 'elastigsearch include flag'
    required: false
    default: false
  python-version:
    description: 'python version'
    required: false
    default: '3.8'
#  use-postgresql:
#    description: 'postgresql include flag'
#    required: false
#    default: false
outputs:
  output1:
    description: 'output status'
    value: 'python-deploy-ghaction:: use-elasticsearch:${{ inputs.use-elasticsearch }}'
#    value: 'python-deploy-ghaction:: use-elasticsearch:${{ inputs.use-elasticsearch }} use-postgresql:${{ inputs.use-postgresql }} success:${{ success() }}'
runs:
  using: 'composite'
  steps: 
    - name: 'debug'
      run: |
        echo 'github.action: ${{ github.action }}'
        echo 'github.action_path: ${{ github.action_path }}'
        echo 'github.event_name: ${{ github.event_name }}'
        echo 'github.job: ${{ github.job }}'
        echo 'github.repository: ${{ github.repository }}'
        echo 'github.workflow: ${{ github.workflow }}'
        echo 'github.workspace: ${{ github.workspace }}'
      shell: bash

#    - name: Run-tests
#      run: |
#        wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
#        [[ -f ./run-tests.sh ]] && ./run-tests.sh
#      shell: bash

#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip wheel setuptools
#        pip install -e .[tests]

#    - name: Test with pytest
#      run: |
#        pytest tests

#    - name: Check manifest
#      run: |
#        check-manifest

#    - name: Build package to publish
#      run: |
#        python setup.py sdist bdist_wheel
        
#    - name: Archive production artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: dist
#        path: dist

